//! MePassa Core Library
//!
//! Core library for MePassa P2P chat platform.
//!
//! ## Architecture: HYBRID P2P + Server
//!
//! - **80% P2P direct:** Messages go peer-to-peer (max privacy, zero cost)
//! - **15% TURN relay:** Fallback when symmetric NAT/firewall
//! - **5% Store & Forward:** Recipient offline (PostgreSQL, 14d TTL)
//!
//! ## Modules
//!
//! - `identity`: Ed25519 keypairs and peer identity management
//! - `crypto`: Signal Protocol E2E encryption
//! - `network`: libp2p P2P networking
//! - `storage`: SQLite local storage
//! - `sync`: CRDTs for multi-device sync
//! - `voip`: WebRTC voice/video calls
//! - `protocol`: Protobuf message definitions
//! - `api`: Public Client API
//! - `ffi`: UniFFI bindings for Kotlin/Swift

// Feature flag helper: video features available with either 'voip' or 'video'
#[cfg(any(feature = "voip", feature = "video"))]
macro_rules! cfg_video {
    ($($item:item)*) => {
        $($item)*
    }
}

#[cfg(not(any(feature = "voip", feature = "video")))]
macro_rules! cfg_video {
    ($($item:item)*) => {}
}

// Re-export public API
// TODO: Uncomment when modules are implemented
// pub use api::{Client, ClientBuilder, Event};
pub use identity::{Identity, Keypair, PublicKey};
// pub use protocol::{Message, MessageContent, MessageType};

// Re-export FFI types (required by UniFFI scaffolding)
pub use ffi::{
    FfiConversation, FfiGroup, FfiMedia, FfiMediaType, FfiMessage, FfiReaction, MePassaClient,
    MePassaFfiError, MessageStatus,
};

// Re-export VoIP FFI types (always available - stubs when voip feature is disabled)
// Note: FfiVideoFrameCallback is auto-generated by UniFFI and available from generated bindings
pub use ffi::{
    FfiCall, FfiCallDirection, FfiCallEndReason, FfiCallState, FfiCallStats, FfiCameraPosition,
    FfiVideoCodec, FfiVideoResolution, FfiVideoStats,
};

// Public modules
pub mod api;
pub mod crypto;
pub mod ffi;
pub mod group;
pub mod identity;
pub mod identity_client;
pub mod media;
pub mod network;
pub mod protocol;
pub mod reactions;
pub mod storage;
pub mod sync;
#[cfg(any(feature = "voip", feature = "video"))]
pub mod voip;
pub mod utils;

/// Library version
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

// Forward declaration for UniFFI callback interface
// The actual trait will be generated by UniFFI scaffolding
pub trait FfiVideoFrameCallback: Send + Sync {
    fn on_video_frame(&self, call_id: String, frame_data: Vec<u8>, width: u32, height: u32);
}

// VoIP control event callback
pub trait FfiVoipEventCallback: Send + Sync {
    fn on_mute_changed(&self, call_id: String, is_muted: bool);
    fn on_speakerphone_changed(&self, call_id: String, enabled: bool);
    fn on_camera_switch_requested(&self, call_id: String);
}

// Include UniFFI scaffolding (after all module declarations)
uniffi::include_scaffolding!("mepassa");

/// Initialize logging system
pub fn init_logging(level: utils::LogLevel) {
    utils::logging::init(level);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_version() {
        assert!(!VERSION.is_empty());
        assert_eq!(VERSION, "0.1.0");
    }
}
